//-----------------------------------------------------MY COLOR SCHEME
#define COLOR_DARK 							0x403F4CFF
#define COLOR_RED 							0xE84855FF
#define COLOR_YELLOW 						0xF9DC5CFF
#define COLOR_BLUE 							0x3185FCFF
#define COLOR_LIGHTBLUE 					0x16E0BDFF

//------------------------------------------------------OTHER DEFINES
#define MYSQL_HOSTNAME						"localhost"
#define MYSQL_USERNAME						"root"
#define MYSQL_PASSWORD						""
#define MYSQL_DATABASE						"scratch_cnr"

#define	BCRYPT_COST							12
#define	SECONDS_TO_LOGIN 					60

#undef	  	MAX_PLAYERS
#define	 	MAX_PLAYERS						50


#define SCM 								SendClientMessage
#define MNLTAG								"{3185FC}MNL:CNR{F9DC5C}"

#define INVALIDCLASS						0
#define CLASS_CIVILIAN						1
#define CLASS_POLICE						2
#define CLASS_FBI							3
#define CLASS_ARMY							4