//-----------------------------------------------------MY COLOR SCHEME
#define COLOR_DARK 							0x403F4CFF
#define COLOR_RED 							0xE84855FF
#define COLOR_YELLOW 						0xF9DC5CFF
#define COLOR_BLUE 							0x3185FCFF
#define COLOR_LIGHTBLUE 					0x16E0BDFF

#define COL_DARK 							"{403F4C}"
#define COL_RED 							"{E84855}"
#define COL_YELLOW 							"{F9DC5C}"
#define COL_BLUE 							"{3185FC}"
#define COL_LIGHTBLUE 						"{16E0BD}"

#define TD_OUTLINE_COLOUR			(0x00000088)

// Colours
#define COLOR_SAMPBLUE				0xa9c4e4FF

#define COLOR_YELLOW2				0xFFFF00FF
#define COLOR_MODERATION			0xFF00FFFF
#define COLOR_RED2					0xE85454FF
#define COLOR_GREEN					0x33AA33FF
#define COLOR_BLUE2					0x33CCFFFF
#define COLOR_ORANGE				0xFFAA00FF
#define COLOR_GREY					0xAFAFAFFF
#define COLOR_PINK					0xFFC0CBFF
#define COLOR_NAVY					0x000080FF
#define COLOR_GOLD					0xB8860BFF
#define COLOR_LIGHTGREEN			0x00FD4DFF
#define COLOR_TEAL					0x008080FF
#define COLOR_BROWN					0xA52A2AFF
#define COLOR_AQUA					0xF0F8FFFF
#define COLOR_PURPLE				0xC2A2DAAA
#define COLOR_BLACK					0x000000FF
#define COLOR_WHITE					0xFFFFFFFF

// Embedding Colours
#define C_SAMPBLUE 		            "{a9c4e4}"
#define C_YELLOW					"{FFFF00}"
#define C_FUCHSIA					"{FF00FF}"
#define C_RED						"{E85454}"
#define C_GREEN						"{33AA33}"
#define C_BLUE						"{33CCFF}"
#define C_PURPLE                    "{C2A2DA}"
#define C_ORANGE					"{FFAA00}"
#define C_GREY						"{AFAFAF}"
#define C_PINK						"{FFC0CB}"
#define C_NAVY						"{000080}"
#define C_GOLD						"{B8860B}"
#define C_LGREEN					"{00FD4D}"
#define C_TEAL						"{008080}"
#define C_BROWN						"{A52A2A}"
#define C_AQUA						"{F0F8FF}"
#define C_MODERATION                "{F5129F}"

#define C_BLACK						"{000000}"
#define C_WHITE						"{FFFFFF}"

//------------------------------------------------------OTHER DEFINES



#define MYSQL_HOSTNAME						"localhost"
#define MYSQL_USERNAME						"root"
#define MYSQL_PASSWORD						"mypassword"
#define MYSQL_DATABASE						"scratch_cnr"

#define	BCRYPT_COST							12
#define	SECONDS_TO_LOGIN 					60

#undef	  	MAX_PLAYERS
#define	 	MAX_PLAYERS						50



#define SCM 								SendClientMessage
#define MNLTAG								"{3185FC}MNL:CNR{F9DC5C}"
#define SERVER_DISCORD						"(discord.gg/m3D6Ff2)"

#define INVALIDCLASS						0
#define CLASS_CIVILIAN						1
#define CLASS_POLICE						2
#define CLASS_FBI							3
#define CLASS_ARMY							4

#define OS_TYPE_ANDROID 					0
#define OS_TYPE_PC 							1
//--------------------------DIALOG MACROS--------------------
#define DIALOGID_MECHMENU                   10
#define DIALOGID_NITROMENU                  11
#define DIALOGID_RAMPSELMENU                12
#define DIALOGID_TIREMENU                   13